# Generated by Django 3.1.12 on 2021-10-20 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20211020_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 23, 4, 4, 205104, tzinfo=utc)),
        ),
    ]
