# Generated by Django 3.2.9 on 2026-06-05 02:43

import datetime
from django.db import migrations, models
from datetime import timezone

utc = timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_auto_20211202_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 2, 43, 1, 745346, tzinfo=utc)),
        ),
    ]
