# Generated by Django 3.2.9 on 2026-06-06 01:58

import datetime
from django.db import migrations, models
from datetime import timezone

utc = timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 6, 1, 58, 18, 823908, tzinfo=utc)),
        ),
    ]
