# Generated by Django 3.2.9 on 2026-06-06 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0010_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 6, 6, 43, 49, 399611, tzinfo=utc)),
        ),
    ]
