# Generated by Django 3.2.9 on 2026-06-06 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0011_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('structural', 'Structural'), ('appliance', 'Appliance'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workorders/static/images'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='recurring_interval',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Recurring interval in days', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
