# Generated by Django 3.2.9 on 2026-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_auto_20260606_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workorders/images'),
        ),
    ]
