# Generated by Django 3.2.25 on 2026-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0013_alter_workorder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
