# Generated by Django 5.2.15 on 2026-06-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='phoneNum',
            new_name='phone_num',
        ),
    ]
