# Generated by Django 5.2.15 on 2026-06-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_phonenum_reservation_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end',
            new_name='checkout',
        ),
    ]
