# Generated by Django 5.2.15 on 2026-06-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_end_reservation_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='start',
            new_name='checkin',
        ),
    ]
