# Generated by Django 5.2.15 on 2026-06-21 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_start_reservation_checkin'),
        ('sites', '0009_site_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='site_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
