# Generated by Django 5.2.15 on 2026-06-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_populate_site_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='site',
        ),
    ]
