# Generated by Django 5.2.15 on 2026-06-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='site_fk',
            new_name='site',
        ),
    ]
