# Generated by Django 5.2.15 on 2026-06-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_rename_site_fk_reservation_site'),
        ('sites', '0009_site_retired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
    ]
