# Generated by Django 3.2.25 on 2026-06-07 01:05

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
      
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE manager_metric RENAME TO metrics_metric;",
                    reverse_sql="ALTER TABLE metrics_metric RENAME TO manager_metric;"
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Metric',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True)),
                        ('site', models.CharField(max_length=4)),
                        ('start', models.DateTimeField()),
                        ('end', models.DateTimeField()),
                        ('canceled', models.BooleanField(default=False)),
                        ('res_type', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=1)),
                        ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.customer')),
                    ],
                ),
            ]
        ),
    ]

