# Generated by Django 3.2.9 on 2026-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_create_initial_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='electric_30amp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='electric_50amp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='lot_type',
            field=models.CharField(choices=[('rv', 'RV'), ('cabin', 'Cabin'), ('tent', 'Tent'), ('pullthrough', 'Pull Through')], default='rv', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='max_length_ft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='sewer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='under_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
