# Generated by Django 3.2.9 on 2026-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20260606_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
    ]
