# Generated by Django 3.2.9 on 2026-06-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
