# Generated by Django 3.2.25 on 2026-06-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='identifier',
            new_name='lot_id',
        ),
    ]
