# Generated by Django 5.2.15 on 2026-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_rename_identifier_site_lot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='lot_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
