# Generated by Django 5.2.15 on 2026-06-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_site_lot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
