# Generated by Django 3.0.6 on 2020-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneNum',
            field=models.CharField(default='888-888-8888', max_length=25),
            preserve_default=False,
        ),
    ]
