# Generated by Django 3.0.6 on 2020-05-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_customer_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(default='task', max_length=10),
        ),
    ]
