# Generated by Django 3.0.6 on 2020-05-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200529_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='site',
            field=models.CharField(max_length=4),
        ),
    ]
