# Generated by Django 3.1.12 on 2021-10-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_customer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
