# Generated by Django 3.1.12 on 2021-10-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_customer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=4)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
