# Generated by Django 3.1.12 on 2021-10-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metric',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.customer'),
        ),
    ]
