# Generated by Django 3.1.12 on 2021-10-14 00:27

from django.db import migrations


def create_metric_from_customer(apps, schema_editor):
    Customer = apps.get_model('manager', 'Customer')
    Metric = apps.get_model('manager', 'Metric')

    customers = Customer.objects.all()
    for customer in customers:
        metric = Metric(site=customer.site, start=customer.start, end=customer.end, customer=customer)
        metric.save()

class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20211013_2348'),
    ]

    operations = [
        migrations.RunPython(create_metric_from_customer),
    ]
