# Generated by Django 3.1.12 on 2021-10-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_metric_res_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='res_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=1),
        ),
    ]
