# Generated by Django 3.1.12 on 2021-10-16 05:35

from django.db import migrations
from ..helpers import get_reservation_type

def reset_reservation_type(apps, schema_editor):
    Metric = apps.get_model('manager', 'Metric')

    metrics = Metric.objects.all()
    for metric in metrics:
        metric.res_type = get_reservation_type(metric.start.isoformat(), metric.end.isoformat())
        metric.save()

class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20211016_0533'),
    ]

    operations = [
        migrations.RunPython(reset_reservation_type),
    ]
