# Generated by Django 3.2.9 on 2026-06-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_set_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_long_term',
            field=models.BooleanField(default=False),
        ),
    ]
