# Generated by Django 3.2.25 on 2026-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_customer_is_long_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
