# Generated by Django 3.2.25 on 2026-06-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20260606_2338'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[

            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Metric',
                ),
            ]
        ),
    ]
