# Generated by Django 3.2.25 on 2026-06-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('metrics', '0002_alter_metric_id'),
        ('manager', '0018_rename_metric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Reservation',
        ),
    ]
