# Generated by Django 3.2.25 on 2026-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_rename_customer_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
